[package]
name = "eth-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
external-memory-tools = {version = "0.1.1", default-features = false}

[dev-dependencies]
alloy-rlp = {version = "0.3.4", features = ["derive"]}
hex = "0.4.3"

[features]
default = ["std"]
std = []
